apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypha-ray-manager
  labels:
    app: hypha-ray-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hypha-ray-manager
  template:
    metadata:
      labels:
        app: hypha-ray-manager
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 8877
        fsGroup: 8877
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: ray-cache
          emptyDir: {}
        - name: temp-dir
          emptyDir: {}
        - name: datasets-volume
          persistentVolumeClaim:
            claimName: datasets-pvc
      containers:
        - name: hypha-ray-manager-container
          image: oeway/hypha-ray-manager:0.1.14
          imagePullPolicy: Always
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: ray-cache
              mountPath: /home/ray/.cache  # Mount the ephemeral volume to the .cache folder
            - name: temp-dir
              mountPath: /tmp
            - name: datasets-volume
              mountPath: /app/datasets
          env:
            - name: RAY_ADDRESS
              value: "ray://raycluster-kuberay-head-svc.ray-cluster.svc.cluster.local:10001"
            - name: HYPHA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: chiron-secrets 
                  key: HYPHA_CHIRON_TOKEN
            - name: HYPHA_SERVER_URL
              value: "http://hypha-server.hypha.svc.cluster.local:9520"
            - name: HYPHA_WORKSPACE
              value: "chiron-platform"
          resources:
            limits:
              cpu: "8"
              memory: "4G"
            requests:
              cpu: "6"
              memory: "3G"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 8877
            seccompProfile:
              type: RuntimeDefault
